CONFIG_ZMK_KEYBOARD_NAME="CorneLP"

# --- CORE SETTINGS ---
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BATTERY_REPORTING=y

# --- FORCE BUILT-IN PLAIN TEXT ---
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# --- DROP BOLD BITMAP GENERATORS ---
CONFIG_LV_FONT_DEFAULT_SMALL=y
CONFIG_LV_TXT_ENC_ASCII=y

# --- DATA INDICATION WIDGETS ---
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

CONFIG_ZMK_POINTING=y
CONFIG_ZMK_STUDIO=y
